// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace amqplib_generator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using amqplib_generator;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class amqp_definitions_c : amqp_definitions_cBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 8 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 amqp amqp = Program.LoadAMQPTypes(); 
            
            #line default
            #line hidden
            this.Write(@"
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#include <stdlib.h>
#ifdef _CRTDBG_MAP_ALLOC
#include <crtdbg.h>
#endif
#include ""amqpvalue.h""
#include ""amqp_definitions.h""
#include ""amqpalloc.h""
#include <stdlib.h>
#include <stdbool.h>

");
            
            #line 23 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
	foreach (section section in amqp.Items.Where(item => item is section)) 
            
            #line default
            #line hidden
            
            #line 24 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
	{ 
            
            #line default
            #line hidden
            
            #line 25 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		List<type> types = new List<type>(); 
            
            #line default
            #line hidden
            
            #line 26 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		types.AddRange(section.Items.Where(item => item is type).Cast<type>()); 
            
            #line default
            #line hidden
            
            #line 27 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		foreach (type type in types) 
            
            #line default
            #line hidden
            
            #line 28 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		{ 
            
            #line default
            #line hidden
            
            #line 29 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			string type_name = type.name.ToLower().Replace('-', '_'); 
            
            #line default
            #line hidden
            
            #line 30 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			if (type.@class == typeClass.composite) 
            
            #line default
            #line hidden
            
            #line 31 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			{ 
            
            #line default
            #line hidden
            
            #line 32 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				var descriptor = type.Items.Where(item => item is descriptor).First() as descriptor; 
            
            #line default
            #line hidden
            this.Write("/* ");
            
            #line 33 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.name));
            
            #line default
            #line hidden
            this.Write(" */\r\n\r\ntypedef struct ");
            
            #line 35 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE_TAG\r\n{\r\n\tAMQP_VALUE composite_value;\r\n} ");
            
            #line 38 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE;\r\n\r\n");
            
            #line 40 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				string arg_list = Program.GetMandatoryArgList(type); 
            
            #line default
            #line hidden
            
            #line 41 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				KeyValuePair<field, int>[] mandatory_args = Program.GetMandatoryArgs(type).ToArray(); 
            
            #line default
            #line hidden
            this.Write("static ");
            
            #line 42 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 42 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_create_internal(void)\r\n{\r\n\t");
            
            #line 44 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 44 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 44 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)amqpalloc_malloc(sizeof(");
            
            #line 44 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE));\r\n\tif (");
            
            #line 45 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance != NULL)\r\n\t{\r\n\t\t");
            
            #line 47 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value = NULL;\r\n\t}\r\n\r\n\treturn ");
            
            #line 50 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance;\r\n}\r\n\r\n");
            
            #line 53 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 53 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_create(");
            
            #line 53 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(arg_list));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n\t");
            
            #line 55 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 55 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 55 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)amqpalloc_malloc(sizeof(");
            
            #line 55 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE));\r\n\tif (");
            
            #line 56 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance != NULL)\r\n\t{\r\n\t\t");
            
            #line 58 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value = amqpvalue_create_composite_with_ulong_descriptor(");
            
            #line 58 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type))));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\tif (");
            
            #line 59 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value == NULL)\r\n\t\t{\r\n\t\t\tamqpalloc_free(");
            
            #line 61 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance);\r\n\t\t\t");
            
            #line 62 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = NULL;\r\n\t\t}\r\n");
            
            #line 64 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				if (mandatory_args.Count() > 0) 
            
            #line default
            #line hidden
            
            #line 65 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            this.Write("\t\telse\r\n\t\t{\r\n");
            
            #line 68 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					for (int i = 0; i < mandatory_args.Count(); i++) 
            
            #line default
            #line hidden
            
            #line 69 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 70 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						string mandatory_arg_name = mandatory_args[i].Key.name.ToLower().Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            this.Write("\t\t\tAMQP_VALUE ");
            
            #line 71 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value;\r\n");
            
            #line 72 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\t\t\tint result = 0;\r\n\r\n");
            
            #line 75 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					for (int i = 0; i < mandatory_args.Count(); i++) 
            
            #line default
            #line hidden
            
            #line 76 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 77 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						string mandatory_arg_type = Program.GetCType(mandatory_args[i].Key.type.ToLower(), mandatory_args[i].Key.multiple == "true").Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 78 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						string mandatory_arg_name = mandatory_args[i].Key.name.ToLower().Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 79 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						if (mandatory_args[i].Key.multiple != "true") 
            
            #line default
            #line hidden
            
            #line 80 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 81 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = amqpvalue_create_");
            
            #line 81 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_args[i].Key.type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 81 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_args[i].Key.name.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("_value);\r\n");
            
            #line 82 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						} 
            
            #line default
            #line hidden
            
            #line 83 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						else 
            
            #line default
            #line hidden
            
            #line 84 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 85 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = ");
            
            #line 85 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_args[i].Key.name.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("_value;\r\n");
            
            #line 86 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						} 
            
            #line default
            #line hidden
            this.Write("\t\t\tif ((result == 0) && (amqpvalue_set_composite_item(");
            
            #line 87 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value, ");
            
            #line 87 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_args[i].Value));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 87 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value) != 0))\r\n\t\t\t{\r\n\t\t\t\tresult = __LINE__;\r\n\t\t\t}\r\n");
            
            #line 91 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 93 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					for (int i = 0; i < mandatory_args.Count(); i++) 
            
            #line default
            #line hidden
            
            #line 94 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 95 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						string mandatory_arg_name = mandatory_args[i].Key.name.ToLower().Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            this.Write("\t\t\tamqpvalue_destroy(");
            
            #line 96 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mandatory_arg_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value);\r\n");
            
            #line 97 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 99 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\treturn ");
            
            #line 102 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance;\r\n}\r\n\r\n");
            
            #line 105 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 105 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_clone(");
            
            #line 105 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE value)\r\n{\r\n\t");
            
            #line 107 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 107 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 107 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)amqpalloc_malloc(sizeof(");
            
            #line 107 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE));\r\n\tif (");
            
            #line 108 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance != NULL)\r\n\t{\r\n\t\t");
            
            #line 110 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value = amqpvalue_clone(((");
            
            #line 110 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)value)->composite_value);\r\n\t\tif (");
            
            #line 111 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value == NULL)\r\n\t\t{\r\n\t\t\tamqpalloc_free(");
            
            #line 113 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance);\r\n\t\t\t");
            
            #line 114 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = NULL;\r\n\t\t}\r\n\t}\r\n\r\n\treturn ");
            
            #line 118 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance;\r\n}\r\n\r\nvoid ");
            
            #line 121 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(");
            
            #line 121 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 121 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n\tif (");
            
            #line 123 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" != NULL)\r\n\t{\r\n\t\t");
            
            #line 125 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 125 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 125 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 125 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tamqpvalue_destroy(");
            
            #line 126 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value);\r\n\t\tamqpalloc_free(");
            
            #line 127 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance);\r\n\t}\r\n}\r\n\r\nAMQP_VALUE amqpvalue_create_");
            
            #line 131 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 131 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 131 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n\tAMQP_VALUE result;\r\n\r\n\tif (");
            
            #line 135 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" == NULL)\r\n\t{\r\n\t\tresult = NULL;\r\n\t}\r\n\telse\r\n\t{\r\n\t\t");
            
            #line 141 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 141 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 141 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 141 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tresult = amqpvalue_clone(");
            
            #line 142 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value);\r\n\t}\r\n\r\n\treturn result;\r\n}\r\n\r\nbool is_");
            
            #line 148 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_type_by_descriptor(AMQP_VALUE descriptor)\r\n{\r\n\tbool result;\r\n\r\n\tuint64_t descrip" +
                    "tor_ulong;\r\n\tif ((amqpvalue_get_ulong(descriptor, &descriptor_ulong) == 0) &&\r\n\t" +
                    "\t(descriptor_ulong == ");
            
            #line 154 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(descriptor).ToString()));
            
            #line default
            #line hidden
            this.Write("))\r\n\t{\r\n\t\tresult = true;\r\n\t}\r\n\telse\r\n\t{\r\n\t\tresult = false;\r\n\t}\r\n\r\n\treturn result;" +
                    "\r\n}\r\n\r\n\r\nint amqpvalue_get_");
            
            #line 167 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("(AMQP_VALUE value, ");
            
            #line 167 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE* ");
            
            #line 167 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle)\r\n{\r\n\tint result;\r\n\t");
            
            #line 170 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 170 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 170 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 170 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_create_internal();\r\n\t*");
            
            #line 171 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle = ");
            
            #line 171 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_instance;\r\n\tif (*");
            
            #line 172 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle == NULL)\r\n\t{\r\n\t\tresult = __LINE__;\r\n\t}\r\n\telse\r\n\t{\r\n\t\tAMQP_VALUE list_valu" +
                    "e = amqpvalue_get_inplace_described_value(value);\r\n\t\tif (list_value == NULL)\r\n\t\t" +
                    "{\r\n\t\t\t");
            
            #line 181 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 181 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\tresult = __LINE__;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tdo\r\n\t\t\t{\r\n");
            
            #line 188 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				int k = 0; 
            
            #line default
            #line hidden
            
            #line 189 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				bool first_one = true; 
            
            #line default
            #line hidden
            
            #line 190 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				foreach (field field in type.Items.Where(item => item is field)) 
            
            #line default
            #line hidden
            
            #line 191 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            
            #line 192 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					string field_name = field.name.ToLower().Replace('-', '_'); 
            
            #line default
            #line hidden
            
            #line 193 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					string c_type = Program.GetCType(field.type, false).Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 194 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					type field_type = Program.GetTypeByName(types, field.type); 
            
            #line default
            #line hidden
            
            #line 195 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					if ((field_type != null) && (field_type.@class == typeClass.composite)) c_type = field_type.name.ToUpper().Replace('-', '_').Replace(':', '_') + "_HANDLE"; 
            
            #line default
            #line hidden
            
            #line 196 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					if (first_one) 
            
            #line default
            #line hidden
            
            #line 197 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            
            #line 198 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						first_one = false; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tAMQP_VALUE item_value;\r\n");
            
            #line 200 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t/* ");
            
            #line 201 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.name));
            
            #line default
            #line hidden
            this.Write(" */\r\n\t\t\t\titem_value = amqpvalue_get_list_item(list_value, ");
            
            #line 202 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(k));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\tif (item_value == NULL)\r\n\t\t\t\t{\r\n");
            
            #line 205 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					if (field.mandatory == "true") 
            
            #line default
            #line hidden
            
            #line 206 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t{\r\n\t\t\t\t\t\t");
            
            #line 208 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 208 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t\t\tbreak;\r\n\t\t\t\t\t}\r\n");
            
            #line 212 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            
            #line 213 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					else 
            
            #line default
            #line hidden
            
            #line 214 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t/* do nothing */\r\n");
            
            #line 216 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t\telse\r\n\t\t\t\t{\r\n");
            
            #line 220 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 if (field.type != "*") 
            
            #line default
            #line hidden
            
            #line 221 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 222 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c_type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 222 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 223 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		if (field.multiple != "true") 
            
            #line default
            #line hidden
            
            #line 224 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tif (amqpvalue_get_");
            
            #line 225 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(item_value, &");
            
            #line 225 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write(") != 0)\r\n");
            
            #line 226 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		} 
            
            #line default
            #line hidden
            
            #line 227 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		else 
            
            #line default
            #line hidden
            
            #line 228 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tAMQP_VALUE ");
            
            #line 229 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_array;\r\n\t\t\t\t\tif ((amqpvalue_get_array(item_value, &");
            
            #line 230 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_array) != 0) &&\r\n\t\t\t\t\t\t(amqpvalue_get_");
            
            #line 231 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(item_value, &");
            
            #line 231 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write(") != 0))\r\n");
            
            #line 232 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t{\r\n");
            
            #line 234 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					if (field.mandatory == "true") 
            
            #line default
            #line hidden
            
            #line 235 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 236 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 236 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t\t\tbreak;\r\n");
            
            #line 239 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            
            #line 240 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					else 
            
            #line default
            #line hidden
            
            #line 241 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tif (amqpvalue_get_type(item_value) != AMQP_TYPE_NULL)\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t");
            
            #line 244 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_destroy(*");
            
            #line 244 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_handle);\r\n\t\t\t\t\t\t\tresult = __LINE__;\r\n\t\t\t\t\t\t\tbreak;\r\n\t\t\t\t\t\t}\r\n");
            
            #line 248 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 					} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t}\r\n\r\n");
            
            #line 251 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            
            #line 252 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 else 
            
            #line default
            #line hidden
            
            #line 253 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            
            #line 254 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tamqpvalue_destroy(item_value);\r\n\t\t\t\t}\r\n");
            
            #line 257 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					k++; 
            
            #line default
            #line hidden
            
            #line 258 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 260 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value = amqpvalue_clone(value);\r\n\r\n\t\t\t\tresult = 0;\r\n\t\t\t} whi" +
                    "le (0);\r\n\t\t}\r\n\t}\r\n\r\n\treturn result;\r\n}\r\n\r\n");
            
            #line 270 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				int j = 0; 
            
            #line default
            #line hidden
            
            #line 271 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				foreach (field field in type.Items.Where(item => item is field)) 
            
            #line default
            #line hidden
            
            #line 272 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            
            #line 273 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					string field_name = field.name.ToLower().Replace('-', '_'); 
            
            #line default
            #line hidden
            
            #line 274 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					string c_type = Program.GetCType(field.type, field.multiple == "true").Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 275 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					type field_type = Program.GetTypeByName(types, field.type); 
            
            #line default
            #line hidden
            
            #line 276 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					if ((field_type != null) && (field_type.@class == typeClass.composite)) c_type = field_type.name.ToUpper().Replace('-', '_').Replace(':', '_') + "_HANDLE"; 
            
            #line default
            #line hidden
            this.Write("int ");
            
            #line 277 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_get_");
            
            #line 277 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 277 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 277 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 277 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c_type));
            
            #line default
            #line hidden
            this.Write("* ");
            
            #line 277 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value)\r\n{\r\n\tint result;\r\n\r\n\tif (");
            
            #line 281 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" == NULL)\r\n\t{\r\n\t\tresult = __LINE__;\r\n\t}\r\n\telse\r\n\t{\r\n\t\t");
            
            #line 287 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 287 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 287 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 287 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tAMQP_VALUE item_value = amqpvalue_get_composite_item_in_place(");
            
            #line 288 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value, ");
            
            #line 288 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\tif (item_value == NULL)\r\n\t\t{\r\n\t\t\tresult = __LINE__;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n");
            
            #line 295 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						if (field.type.Replace('-', '_').Replace(':', '_') == "*") 
            
            #line default
            #line hidden
            
            #line 296 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t*");
            
            #line 297 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value = item_value;\r\n\t\t\tresult = 0;\r\n");
            
            #line 299 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						} 
            
            #line default
            #line hidden
            
            #line 300 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						else 
            
            #line default
            #line hidden
            
            #line 301 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						{ 
            
            #line default
            #line hidden
            
            #line 302 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
							if (field.multiple != "true") 
            
            #line default
            #line hidden
            
            #line 303 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
							{ 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (amqpvalue_get_");
            
            #line 304 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.type.Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(item_value, ");
            
            #line 304 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value) != 0)\r\n");
            
            #line 305 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
							} 
            
            #line default
            #line hidden
            
            #line 306 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
							else 
            
            #line default
            #line hidden
            
            #line 307 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
							{ 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (amqpvalue_get_array(item_value, ");
            
            #line 308 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value) != 0)\r\n");
            
            #line 309 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
							} 
            
            #line default
            #line hidden
            this.Write("\t\t\t{\r\n\t\t\t\tresult = __LINE__;\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tresult = 0;\r\n\t\t\t}\r\n");
            
            #line 317 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
						} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t}\r\n\r\n\treturn result;\r\n}\r\n\r\nint ");
            
            #line 324 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_set_");
            
            #line 324 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 324 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_HANDLE ");
            
            #line 324 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 324 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(c_type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 324 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value)\r\n{\r\n\tint result;\r\n\r\n\tif (");
            
            #line 328 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(" == NULL)\r\n\t{\r\n\t\tresult = __LINE__;\r\n\t}\r\n\telse\r\n\t{\r\n\t\t");
            
            #line 334 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE* ");
            
            #line 334 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance = (");
            
            #line 334 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_INSTANCE*)");
            
            #line 334 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 335 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 if (c_type != "AMQP_VALUE") 
            
            #line default
            #line hidden
            
            #line 336 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            this.Write("\t\tAMQP_VALUE ");
            
            #line 337 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = amqpvalue_create_");
            
            #line 337 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.type.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 337 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value);\r\n");
            
            #line 338 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            
            #line 339 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 else 
            
            #line default
            #line hidden
            
            #line 340 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 { 
            
            #line default
            #line hidden
            this.Write("\t\tAMQP_VALUE ");
            
            #line 341 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value = amqpvalue_clone(");
            
            #line 341 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_value);\r\n");
            
            #line 342 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\tif (");
            
            #line 343 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value == NULL)\r\n\t\t{\r\n\t\t\tresult = __LINE__;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tif (amqpva" +
                    "lue_set_composite_item(");
            
            #line 349 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name));
            
            #line default
            #line hidden
            this.Write("_instance->composite_value, ");
            
            #line 349 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 349 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value) != 0)\r\n\t\t\t{\r\n\t\t\t\tresult = __LINE__;\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tresult" +
                    " = 0;\r\n\t\t\t}\r\n\r\n\t\t\tamqpvalue_destroy(");
            
            #line 358 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field_name));
            
            #line default
            #line hidden
            this.Write("_amqp_value);\r\n\t\t}\r\n\t}\r\n\r\n\treturn result;\r\n}\r\n\r\n");
            
            #line 365 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					j++; 
            
            #line default
            #line hidden
            
            #line 366 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 368 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			} 
            
            #line default
            #line hidden
            
            #line 369 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			else if (type.@class == typeClass.restricted) 
            
            #line default
            #line hidden
            
            #line 370 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			{ 
            
            #line default
            #line hidden
            
            #line 371 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				string c_type = Program.GetCType(type.source, false).Replace('-', '_').Replace(':', '_'); 
            
            #line default
            #line hidden
            
            #line 372 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				bool hasDescriptor = (type.Items != null) && (type.Items.Where(item => item is descriptor).Count() > 0); 
            
            #line default
            #line hidden
            this.Write("/* ");
            
            #line 373 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.name));
            
            #line default
            #line hidden
            this.Write(" */\r\n\r\n");
            
            #line 375 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				if (c_type != "AMQP_VALUE") 
            
            #line default
            #line hidden
            
            #line 376 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            
            #line 377 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					if (!hasDescriptor) 
            
            #line default
            #line hidden
            
            #line 378 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            this.Write("AMQP_VALUE amqpvalue_create_");
            
            #line 379 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 379 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write(" value)\r\n{\r\n\treturn amqpvalue_create_");
            
            #line 381 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.source.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(value);\r\n}\r\n");
            
            #line 383 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            
            #line 384 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					else 
            
            #line default
            #line hidden
            
            #line 385 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            this.Write("AMQP_VALUE amqpvalue_create_");
            
            #line 386 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 386 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write(" value)\r\n{\r\n\tAMQP_VALUE result;\r\n\tAMQP_VALUE described_value = amqpvalue_create_");
            
            #line 389 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.source.ToLower().Replace('-', '_').Replace(':', '_')));
            
            #line default
            #line hidden
            this.Write("(value);\r\n\tif (described_value == NULL)\r\n\t{\r\n\t\tresult = NULL;\r\n\t}\r\n\telse\r\n\t{\r\n\t\tA" +
                    "MQP_VALUE descriptor = amqpvalue_create_ulong(");
            
            #line 396 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type))));
            
            #line default
            #line hidden
            this.Write(@");
		if (descriptor == NULL)
		{
			result = NULL;
		}
		else
		{
			result = amqpvalue_create_described(amqpvalue_clone(descriptor), amqpvalue_clone(described_value));

			amqpvalue_destroy(descriptor);
		}

		amqpvalue_destroy(described_value);
	}

	return result;
}

bool is_");
            
            #line 414 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_type_by_descriptor(AMQP_VALUE descriptor)\r\n{\r\n\tbool result;\r\n\r\n\tuint64_t descrip" +
                    "tor_ulong;\r\n\tif ((amqpvalue_get_ulong(descriptor, &descriptor_ulong) == 0) &&\r\n\t" +
                    "\t(descriptor_ulong == ");
            
            #line 420 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type)).ToString()));
            
            #line default
            #line hidden
            this.Write("))\r\n\t{\r\n\t\tresult = true;\r\n\t}\r\n\telse\r\n\t{\r\n\t\tresult = false;\r\n\t}\r\n\r\n\treturn result;" +
                    "\r\n}\r\n");
            
            #line 431 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            
            #line 432 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            
            #line 433 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				else 
            
            #line default
            #line hidden
            
            #line 434 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				{ 
            
            #line default
            #line hidden
            
            #line 435 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					if (!hasDescriptor) 
            
            #line default
            #line hidden
            
            #line 436 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            this.Write("AMQP_VALUE amqpvalue_create_");
            
            #line 437 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("(AMQP_VALUE value)\r\n{\r\n\treturn amqpvalue_clone(value);\r\n}\r\n");
            
            #line 441 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            
            #line 442 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					else 
            
            #line default
            #line hidden
            
            #line 443 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					{ 
            
            #line default
            #line hidden
            this.Write("AMQP_VALUE amqpvalue_create_");
            
            #line 444 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("(AMQP_VALUE value)\r\n{\r\n\tAMQP_VALUE result;\r\n\tAMQP_VALUE described_value = amqpval" +
                    "ue_clone(value);\r\n\tif (described_value == NULL)\r\n\t{\r\n\t\tresult = NULL;\r\n\t}\r\n\telse" +
                    "\r\n\t{\r\n\t\tAMQP_VALUE descriptor = amqpvalue_create_ulong(");
            
            #line 454 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type))));
            
            #line default
            #line hidden
            this.Write(@");
		if (descriptor == NULL)
		{
			result = NULL;
		}
		else
		{
			result = amqpvalue_create_described(amqpvalue_clone(descriptor), amqpvalue_clone(described_value));

			amqpvalue_destroy(descriptor);
		}

		amqpvalue_destroy(described_value);
	}

	return result;
}

bool is_");
            
            #line 472 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type_name.ToLower()));
            
            #line default
            #line hidden
            this.Write("_type_by_descriptor(AMQP_VALUE descriptor)\r\n{\r\n\tbool result;\r\n\r\n\tuint64_t descrip" +
                    "tor_ulong;\r\n\tif ((amqpvalue_get_ulong(descriptor, &descriptor_ulong) == 0) &&\r\n\t" +
                    "\t(descriptor_ulong == ");
            
            #line 478 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Program.GetDescriptorCode(Program.GetDescriptor(type)).ToString()));
            
            #line default
            #line hidden
            this.Write("))\r\n\t{\r\n\t\tresult = true;\r\n\t}\r\n\telse\r\n\t{\r\n\t\tresult = false;\r\n\t}\r\n\r\n\treturn result;" +
                    "\r\n}\r\n");
            
            #line 489 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
					} 
            
            #line default
            #line hidden
            
            #line 490 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
				} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 492 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
			} 
            
            #line default
            #line hidden
            
            #line 493 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
		} 
            
            #line default
            #line hidden
            
            #line 494 "D:\azure-uamqp-c\uamqp_generator\amqp_definitions_c.tt"
	} 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class amqp_definitions_cBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
